// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -destination=../mocks/processer.go -package=mocks -source=processor.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcesser is a mock of Processer interface.
type MockProcesser struct {
	ctrl     *gomock.Controller
	recorder *MockProcesserMockRecorder
}

// MockProcesserMockRecorder is the mock recorder for MockProcesser.
type MockProcesserMockRecorder struct {
	mock *MockProcesser
}

// NewMockProcesser creates a new mock instance.
func NewMockProcesser(ctrl *gomock.Controller) *MockProcesser {
	mock := &MockProcesser{ctrl: ctrl}
	mock.recorder = &MockProcesserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcesser) EXPECT() *MockProcesserMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockProcesser) Process(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockProcesserMockRecorder) Process(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockProcesser)(nil).Process), data)
}
