package nmea

type midAllocation struct {
	MID  uint16
	Loc  string
	Code []string
}

// MidList is the list of identifiers.
var MidList []midAllocation //nolint: gochecknoglobals

func init() { //nolint: funlen,gochecknoinits,maintidx
	MidList = []midAllocation{
		{MID: 201, Loc: "Albania", Code: []string{"AL"}},
		{MID: 202, Loc: "Andorra", Code: []string{"AD"}},
		{MID: 203, Loc: "Austria", Code: []string{"AT"}},
		{MID: 204, Loc: "Azores", Code: []string{"PT"}},
		{MID: 205, Loc: "Belgium", Code: []string{"BE"}},
		{MID: 206, Loc: "Belarus", Code: []string{"BY"}},
		{MID: 207, Loc: "Bulgaria", Code: []string{"BG"}},
		{MID: 208, Loc: "Vatican City State", Code: []string{"VA"}},
		{MID: 209, Loc: "Cyprus", Code: []string{"CY"}},
		{MID: 210, Loc: "Cyprus", Code: []string{"CY"}},
		{MID: 211, Loc: "Germany", Code: []string{"DE"}},
		{MID: 212, Loc: "Cyprus", Code: []string{"CY"}},
		{MID: 213, Loc: "Georgia", Code: []string{"GE"}},
		{MID: 214, Loc: "Moldova", Code: []string{"MD"}},
		{MID: 215, Loc: "Malta", Code: []string{"MT"}},
		{MID: 216, Loc: "Armenia", Code: []string{"AM"}},
		{MID: 218, Loc: "Germany", Code: []string{"DE"}},
		{MID: 219, Loc: "Denmark", Code: []string{"DK"}},
		{MID: 220, Loc: "Denmark", Code: []string{"DK"}},
		{MID: 224, Loc: "Spain", Code: []string{"ES"}},
		{MID: 225, Loc: "Spain", Code: []string{"ES"}},
		{MID: 226, Loc: "France", Code: []string{"FR"}},
		{MID: 227, Loc: "France", Code: []string{"FR"}},
		{MID: 228, Loc: "France", Code: []string{"FR"}},
		{MID: 229, Loc: "Malta", Code: []string{"MT"}},
		{MID: 230, Loc: "Finland", Code: []string{"FI"}},
		{MID: 231, Loc: "Faroe Islands - Denmark", Code: []string{"DK"}},
		{MID: 232, Loc: "United Kingdom of Great Britain and Northern Ireland", Code: []string{"UK"}},
		{MID: 233, Loc: "United Kingdom of Great Britain and Northern Ireland", Code: []string{"UK"}},
		{MID: 234, Loc: "United Kingdom of Great Britain and Northern Ireland", Code: []string{"UK"}},
		{MID: 235, Loc: "United Kingdom of Great Britain and Northern Ireland", Code: []string{"UK"}},
		{MID: 236, Loc: "Gibraltar", Code: []string{"GI", "UK"}},
		{MID: 237, Loc: "Greece", Code: []string{"GR"}},
		{MID: 238, Loc: "Croatia", Code: []string{"HR"}},
		{MID: 239, Loc: "Greece", Code: []string{"GR"}},
		{MID: 240, Loc: "Greece", Code: []string{"GR"}},
		{MID: 241, Loc: "Greece", Code: []string{"GR"}},
		{MID: 242, Loc: "Morocco", Code: []string{"MA"}},
		{MID: 243, Loc: "Hungary", Code: []string{"HU"}},
		{MID: 244, Loc: "Netherlands", Code: []string{"NL"}},
		{MID: 245, Loc: "Netherlands", Code: []string{"NL"}},
		{MID: 246, Loc: "Netherlands", Code: []string{"NL"}},
		{MID: 247, Loc: "Italy", Code: []string{"IT"}},
		{MID: 248, Loc: "Malta", Code: []string{"MT"}},
		{MID: 249, Loc: "Malta", Code: []string{"MT"}},
		{MID: 250, Loc: "Ireland", Code: []string{"IE"}},
		{MID: 251, Loc: "Iceland", Code: []string{"IS"}},
		{MID: 252, Loc: "Liechtenstein", Code: []string{"LI"}},
		{MID: 253, Loc: "Luxembourg", Code: []string{"LU"}},
		{MID: 254, Loc: "Monaco", Code: []string{"MC"}},
		{MID: 255, Loc: "Madeira", Code: []string{"PT", "PT"}},
		{MID: 256, Loc: "Malta", Code: []string{"MT"}},
		{MID: 257, Loc: "Norway", Code: []string{"NO"}},
		{MID: 258, Loc: "Norway", Code: []string{"NO"}},
		{MID: 259, Loc: "Norway", Code: []string{"NO"}},
		{MID: 261, Loc: "Poland", Code: []string{"PL"}},
		{MID: 262, Loc: "Montenegro", Code: []string{"ME"}},
		{MID: 263, Loc: "Portugal", Code: []string{"PT", "PT"}},
		{MID: 264, Loc: "Romania", Code: []string{"RO"}},
		{MID: 265, Loc: "Sweden", Code: []string{"SE"}},
		{MID: 266, Loc: "Sweden", Code: []string{"SE"}},
		{MID: 267, Loc: "Slovak Republic", Code: []string{"SK"}},
		{MID: 268, Loc: "San Marino", Code: []string{"SM"}},
		{MID: 269, Loc: "Switzerland", Code: []string{"CH"}},
		{MID: 270, Loc: "Czech Republic", Code: []string{"CZ"}},
		{MID: 271, Loc: "Turkey", Code: []string{"TR"}},
		{MID: 272, Loc: "Ukraine", Code: []string{"UA"}},
		{MID: 273, Loc: "Russian Federation", Code: []string{"RU"}},
		{MID: 274, Loc: "The Former Yugoslav Republic of Macedonia", Code: []string{"MK"}},
		{MID: 275, Loc: "Latvia", Code: []string{"LV"}},
		{MID: 276, Loc: "Estonia", Code: []string{"EE"}},
		{MID: 277, Loc: "Lithuania", Code: []string{"LT"}},
		{MID: 278, Loc: "Slovenia", Code: []string{"SI"}},
		{MID: 279, Loc: "Serbia", Code: []string{"RS"}},
		{MID: 301, Loc: "Anguilla", Code: []string{"AI", "UK"}},
		{MID: 303, Loc: "Alaska", Code: []string{"US"}},
		{MID: 304, Loc: "Antigua and Barbuda", Code: []string{"AG"}},
		{MID: 305, Loc: "Antigua and Barbuda", Code: []string{"AG"}},
		{MID: 306, Loc: "Curacao, Sint Maarten, Bonaire, Sint Eustatius and Saba", Code: []string{"NL"}},
		{MID: 307, Loc: "Aruba – Netherlands", Code: []string{"NL"}},
		{MID: 308, Loc: "Bahamas", Code: []string{"BS"}},
		{MID: 309, Loc: "Bahamas", Code: []string{"BS"}},
		{MID: 310, Loc: "Bermuda", Code: []string{"BM", "UK"}},
		{MID: 311, Loc: "Bahamas", Code: []string{"BS"}},
		{MID: 312, Loc: "Belize", Code: []string{"BZ"}},
		{MID: 314, Loc: "Barbados", Code: []string{"BB"}},
		{MID: 316, Loc: "Canada", Code: []string{"CA"}},
		{MID: 319, Loc: "Cayman Islands", Code: []string{"KY", "UK"}},
		{MID: 321, Loc: "Costa Rica", Code: []string{"CR"}},
		{MID: 323, Loc: "Cuba", Code: []string{"CU"}},
		{MID: 325, Loc: "Dominica", Code: []string{"DM"}},
		{MID: 327, Loc: "Dominican Republic", Code: []string{"DO"}},
		{MID: 329, Loc: "Guadeloupe", Code: []string{"GP", "FR"}},
		{MID: 330, Loc: "Grenada", Code: []string{"GD"}},
		{MID: 331, Loc: "Greenland - Denmark", Code: []string{"DK"}},
		{MID: 332, Loc: "Guatemala", Code: []string{"GT"}},
		{MID: 334, Loc: "Honduras", Code: []string{"HN"}},
		{MID: 336, Loc: "Haiti", Code: []string{"HT"}},
		{MID: 338, Loc: "United States of America", Code: []string{"US"}},
		{MID: 339, Loc: "Jamaica", Code: []string{"JM"}},
		{MID: 341, Loc: "Saint Kitts and Nevis", Code: []string{"KN"}},
		{MID: 343, Loc: "Saint Lucia", Code: []string{"LC"}},
		{MID: 345, Loc: "Mexico", Code: []string{"MX"}},
		{MID: 347, Loc: "Martinique", Code: []string{"MQ", "FR"}},
		{MID: 348, Loc: "Montserrat", Code: []string{"MS"}},
		{MID: 350, Loc: "Nicaragua", Code: []string{"NI"}},
		{MID: 351, Loc: "Panama", Code: []string{"PA"}},
		{MID: 352, Loc: "Panama", Code: []string{"PA"}},
		{MID: 353, Loc: "Panama", Code: []string{"PA"}},
		{MID: 354, Loc: "Panama", Code: []string{"PA"}},
		{MID: 355, Loc: " - ", Code: []string{}},
		{MID: 356, Loc: " - ", Code: []string{}},
		{MID: 357, Loc: " - ", Code: []string{}},
		{MID: 358, Loc: "Puerto Rico", Code: []string{"PR", "US"}},
		{MID: 359, Loc: "El Salvador", Code: []string{"SV"}},
		{MID: 361, Loc: "Saint Pierre and Miquelon", Code: []string{"PM", "FR"}},
		{MID: 362, Loc: "Trinidad and Tobago", Code: []string{"TT"}},
		{MID: 364, Loc: "Turks and Caicos Islands", Code: []string{"TC", "UK"}},
		{MID: 366, Loc: "United States of America", Code: []string{"US", "US"}},
		{MID: 367, Loc: "United States of America", Code: []string{"US", "US"}},
		{MID: 368, Loc: "United States of America", Code: []string{"US", "US"}},
		{MID: 369, Loc: "United States of America", Code: []string{"US", "US"}},
		{MID: 370, Loc: "Panama", Code: []string{"PA"}},
		{MID: 371, Loc: "Panama", Code: []string{"PA"}},
		{MID: 372, Loc: "Panama", Code: []string{"PA"}},
		{MID: 373, Loc: "Panama", Code: []string{"PA"}},
		{MID: 375, Loc: "Saint Vincent and the Grenadines", Code: []string{"VC"}},
		{MID: 376, Loc: "Saint Vincent and the Grenadines", Code: []string{"VC"}},
		{MID: 377, Loc: "Saint Vincent and the Grenadines", Code: []string{"VC"}},
		{MID: 378, Loc: "British Virgin Islands", Code: []string{"UK"}},
		{MID: 379, Loc: "United States Virgin Islands", Code: []string{"US"}},
		{MID: 401, Loc: "Afghanistan", Code: []string{"AF"}},
		{MID: 403, Loc: "Saudi Arabia", Code: []string{"SA"}},
		{MID: 405, Loc: "Bangladesh", Code: []string{"BD"}},
		{MID: 408, Loc: "Bahrain", Code: []string{"BH"}},
		{MID: 410, Loc: "Bahrain", Code: []string{"BH"}},
		{MID: 412, Loc: "China", Code: []string{"CN"}},
		{MID: 413, Loc: "China", Code: []string{"CN"}},
		{MID: 414, Loc: "China", Code: []string{"CN"}},
		{MID: 416, Loc: "Taiwan", Code: []string{"TW"}},
		{MID: 417, Loc: "Sri Lanka", Code: []string{"LK"}},
		{MID: 419, Loc: "India", Code: []string{"IN"}},
		{MID: 422, Loc: "Iran", Code: []string{"IR"}},
		{MID: 423, Loc: "Azerbaijan", Code: []string{"AZ"}},
		{MID: 425, Loc: "Iraq", Code: []string{"IQ"}},
		{MID: 428, Loc: "Israel", Code: []string{"IL"}},
		{MID: 431, Loc: "Japan", Code: []string{"JP"}},
		{MID: 432, Loc: "Japan", Code: []string{"JP"}},
		{MID: 434, Loc: "Turkmenistan", Code: []string{"TM"}},
		{MID: 436, Loc: "Kazakhstan", Code: []string{"KZ"}},
		{MID: 437, Loc: "Uzbekistan", Code: []string{"UZ"}},
		{MID: 438, Loc: "Jordan", Code: []string{"JO"}},
		{MID: 440, Loc: "Korea", Code: []string{"KR"}},
		{MID: 441, Loc: "Korea", Code: []string{"KR"}},
		{MID: 443, Loc: "Palestine", Code: []string{"PS"}},
		{MID: 445, Loc: "Democratic People's Republic of Korea", Code: []string{"KP"}},
		{MID: 447, Loc: "Kuwait", Code: []string{"KW"}},
		{MID: 450, Loc: "Lebanon", Code: []string{"LB"}},
		{MID: 451, Loc: "Kyrgyz Republic", Code: []string{"KG"}},
		{MID: 453, Loc: "Macao", Code: []string{"MO"}},
		{MID: 455, Loc: "Maldives", Code: []string{"MV"}},
		{MID: 457, Loc: "Mongolia", Code: []string{"MN"}},
		{MID: 459, Loc: "Nepal", Code: []string{"NP"}},
		{MID: 461, Loc: "Oman", Code: []string{"OM"}},
		{MID: 463, Loc: "Pakistan", Code: []string{"PK"}},
		{MID: 466, Loc: "Qatar", Code: []string{"QA"}},
		{MID: 468, Loc: "Syrian Arab Republic", Code: []string{"SY"}},
		{MID: 470, Loc: "United Arab Emirates", Code: []string{"AE"}},
		{MID: 472, Loc: "Tajikistan", Code: []string{"TJ"}},
		{MID: 473, Loc: "Yemen", Code: []string{"YE"}},
		{MID: 475, Loc: "Yemen", Code: []string{"YE"}},
		{MID: 477, Loc: "Hong Kong", Code: []string{"HK"}},
		{MID: 478, Loc: "Bosnia and Herzegovina", Code: []string{"BA"}},
		{MID: 501, Loc: "Adelie Land", Code: []string{"FR"}},
		{MID: 503, Loc: "Australia", Code: []string{"AU"}},
		{MID: 506, Loc: "Myanmar", Code: []string{"MM"}},
		{MID: 508, Loc: "Brunei Darussalam", Code: []string{"BN"}},
		{MID: 510, Loc: "Micronesia", Code: []string{"FM"}},
		{MID: 511, Loc: "Palau", Code: []string{"PW"}},
		{MID: 512, Loc: "New Zealand", Code: []string{"NZ"}},
		{MID: 514, Loc: "Cambodia", Code: []string{"KH"}},
		{MID: 515, Loc: "Cambodia", Code: []string{"KH"}},
		{MID: 516, Loc: "Christmas Island", Code: []string{"AU"}},
		{MID: 518, Loc: "Cook Islands - New Zealand", Code: []string{"NZ"}},
		{MID: 520, Loc: "Fiji", Code: []string{"FJ"}},
		{MID: 523, Loc: "Cocos (Keeling) Islands", Code: []string{"AU"}},
		{MID: 525, Loc: "Indonesia", Code: []string{"ID"}},
		{MID: 529, Loc: "Kiribati", Code: []string{"KI"}},
		{MID: 531, Loc: "Lao People's Democratic Republic", Code: []string{"LA"}},
		{MID: 533, Loc: "Malaysia", Code: []string{"MY"}},
		{MID: 536, Loc: "Northern Mariana Islands", Code: []string{"MP", "US"}},
		{MID: 538, Loc: "Marshall Islands (Republic of the)", Code: []string{"MH"}},
		{MID: 540, Loc: "New Caledonia", Code: []string{"FR"}},
		{MID: 542, Loc: "Niue", Code: []string{"NZ"}},
		{MID: 544, Loc: "Nauru", Code: []string{"NR"}},
		{MID: 546, Loc: "French Polynesia - France", Code: []string{"FR"}},
		{MID: 548, Loc: "Philippines", Code: []string{"PH"}},
		{MID: 553, Loc: "Papua New Guinea", Code: []string{"PG"}},
		{MID: 555, Loc: "Pitcairn Island", Code: []string{"UK"}},
		{MID: 557, Loc: "Solomon Islands", Code: []string{"SB"}},
		{MID: 559, Loc: "American Samoa", Code: []string{"AS", "US"}},
		{MID: 561, Loc: "Samoa", Code: []string{"WS"}},
		{MID: 563, Loc: "Singapore", Code: []string{"SG"}},
		{MID: 564, Loc: "Singapore", Code: []string{"SG"}},
		{MID: 565, Loc: "Singapore", Code: []string{"SG"}},
		{MID: 566, Loc: "Singapore", Code: []string{"SG"}},
		{MID: 567, Loc: "Thailand", Code: []string{"TH"}},
		{MID: 570, Loc: "Tonga", Code: []string{"TO"}},
		{MID: 572, Loc: "Tuvalu", Code: []string{"TV"}},
		{MID: 574, Loc: "Viet Nam", Code: []string{"VN"}},
		{MID: 576, Loc: "Vanuatu", Code: []string{"VU"}},
		{MID: 577, Loc: "Vanuatu", Code: []string{"VU"}},
		{MID: 578, Loc: "Wallis and Futuna Islands", Code: []string{"FR"}},
		{MID: 601, Loc: "South Africa", Code: []string{"ZA"}},
		{MID: 603, Loc: "Angola", Code: []string{"AO"}},
		{MID: 605, Loc: "Algeria", Code: []string{"DZ"}},
		{MID: 607, Loc: "Saint Paul and Amsterdam Islands", Code: []string{"FR"}},
		{MID: 608, Loc: "Ascension Island", Code: []string{"UK"}},
		{MID: 609, Loc: "Burundi", Code: []string{"BI"}},
		{MID: 610, Loc: "Benin", Code: []string{"BJ"}},
		{MID: 611, Loc: "Botswana", Code: []string{"BW"}},
		{MID: 612, Loc: "Central African Republic", Code: []string{"CF"}},
		{MID: 613, Loc: "Cameroon", Code: []string{"CM"}},
		{MID: 615, Loc: "Congo", Code: []string{"CG"}},
		{MID: 616, Loc: "Comoros", Code: []string{"KM"}},
		{MID: 617, Loc: "Cabo Verde", Code: []string{"CV"}},
		{MID: 618, Loc: "Crozet Archipelago", Code: []string{"FR"}},
		{MID: 619, Loc: "Cote d'Ivoire", Code: []string{"CI"}},
		{MID: 620, Loc: "Comoros", Code: []string{"KM"}},
		{MID: 621, Loc: "Djibouti", Code: []string{"DJ"}},
		{MID: 622, Loc: "Egypt", Code: []string{"EG"}},
		{MID: 624, Loc: "Ethiopia", Code: []string{"ET"}},
		{MID: 625, Loc: "Eritrea", Code: []string{"ER"}},
		{MID: 626, Loc: "Gabonese Republic", Code: []string{"GA"}},
		{MID: 627, Loc: "Ghana", Code: []string{"GH"}},
		{MID: 629, Loc: "Gambia", Code: []string{"GM"}},
		{MID: 630, Loc: "Guinea-Bissau", Code: []string{"GW"}},
		{MID: 631, Loc: "Equatorial Guinea", Code: []string{"GQ"}},
		{MID: 632, Loc: "Guinea", Code: []string{"GN"}},
		{MID: 633, Loc: "Burkina Faso", Code: []string{"BF"}},
		{MID: 634, Loc: "Kenya", Code: []string{"KE"}},
		{MID: 635, Loc: "Kerguelen Islands - France", Code: []string{"FR"}},
		{MID: 636, Loc: "Liberia", Code: []string{"LR"}},
		{MID: 637, Loc: "Liberia", Code: []string{"LR"}},
		{MID: 638, Loc: "South Sudan", Code: []string{"SS"}},
		{MID: 642, Loc: "Libya", Code: []string{"LY"}},
		{MID: 644, Loc: "Lesotho", Code: []string{"LS"}},
		{MID: 645, Loc: "Mauritius", Code: []string{"MU"}},
		{MID: 647, Loc: "Madagascar", Code: []string{"MG"}},
		{MID: 649, Loc: "Mali", Code: []string{"ML"}},
		{MID: 650, Loc: "Mozambique", Code: []string{"MZ"}},
		{MID: 654, Loc: "Mauritania", Code: []string{"MR"}},
		{MID: 655, Loc: "Malawi", Code: []string{"MW"}},
		{MID: 656, Loc: "Niger", Code: []string{"NE"}},
		{MID: 657, Loc: "Nigeria", Code: []string{"NG"}},
		{MID: 659, Loc: "Namibia", Code: []string{"NA"}},
		{MID: 660, Loc: "Reunion", Code: []string{"FR"}},
		{MID: 661, Loc: "Rwanda", Code: []string{"RW"}},
		{MID: 662, Loc: "Sudan", Code: []string{"SD"}},
		{MID: 663, Loc: "Senegal", Code: []string{"SN"}},
		{MID: 664, Loc: "Seychelles", Code: []string{"SC"}},
		{MID: 665, Loc: "Saint Helena", Code: []string{"UK"}},
		{MID: 666, Loc: "Somalia", Code: []string{"SO"}},
		{MID: 667, Loc: "Sierra Leone", Code: []string{"SL"}},
		{MID: 668, Loc: "Sao Tome and Principe", Code: []string{"ST"}},
		{MID: 669, Loc: "Swaziland", Code: []string{"SZ"}},
		{MID: 670, Loc: "Chad", Code: []string{"TD"}},
		{MID: 671, Loc: "Togolese Republic", Code: []string{"TG"}},
		{MID: 672, Loc: "Tunisia", Code: []string{"TN"}},
		{MID: 674, Loc: "Tanzania", Code: []string{"TZ"}},
		{MID: 675, Loc: "Uganda", Code: []string{"UG"}},
		{MID: 676, Loc: "Democratic Republic of the Congo", Code: []string{"CD"}},
		{MID: 677, Loc: "Tanzania", Code: []string{"TZ"}},
		{MID: 678, Loc: "Zambia", Code: []string{"ZM"}},
		{MID: 679, Loc: "Zimbabwe", Code: []string{"ZW"}},
		{MID: 701, Loc: "Argentine", Code: []string{"AR"}},
		{MID: 710, Loc: "Brazil", Code: []string{"BR"}},
		{MID: 720, Loc: "Bolivia", Code: []string{"BO"}},
		{MID: 725, Loc: "Chile", Code: []string{"CL"}},
		{MID: 730, Loc: "Colombia", Code: []string{"CO"}},
		{MID: 735, Loc: "Ecuador", Code: []string{"EC"}},
		{MID: 740, Loc: "Falkland Islands", Code: []string{"UK"}},
		{MID: 745, Loc: "Guiana", Code: []string{"FR"}},
		{MID: 750, Loc: "Guyana", Code: []string{"GY"}},
		{MID: 755, Loc: "Paraguay", Code: []string{"PY"}},
		{MID: 760, Loc: "Peru", Code: []string{"PE"}},
		{MID: 765, Loc: "Suriname", Code: []string{"SR"}},
		{MID: 770, Loc: "Uruguay", Code: []string{"UY"}},
	}
}
